name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login into Docker
      run: docker login -u ${{secrets.DOCKERHUB_PYTHON_USER}} -p ${{secrets.DOCKERHUB_PYTHON_TOKEN}}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./app-1 -t charmbracelets/react-app-sample
      
    - name: Build the Docker image
      run: docker push charmbracelets/react-app-sample
